name: Tests for Mongodb

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mongodb:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '#Skip')"
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - name: Set up MongoDB 4.4
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 4.4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Gradle test
        run: ./gradlew :alkaid-mongodb:test -Dtest.single="com/alkaidmc/alkaid/mongodb/AlkaidMongodbTest"

      - name: Upload fail reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: mongodb-test-failure
          path: alkaid-mongodb/build/reports